framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            test_runner:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: test_runner
                retry_strategy:
                    max_retries: 2
                    delay: 10000
                    multiplier: 3
            scheduler_test_runner:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: scheduler_test_runner
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async

            # Test Runner messages
            App\Message\TestRunMessage: test_runner
            App\Message\ScheduledTestRunMessage: scheduler_test_runner
